spring.application.name=training
server.servlet.context-path=/training-uat

logging.level.com.java.training.*=DEBUG
logging.level.org.springframework.web.servlet.*=TRACE
spring.output.ansi.enabled=ALWAYS
spring.main.banner-mode=off